--CREATE FUNCTION FN_KAYITGOSTER()
--RETURNS NVARCHAR (50)
--AS 
--BEGIN
--	DECLARE @Sayi INT 
--	DEClarE @Metin NVARCHAR (50)
--	SELECT @Sayi =COUNT(*) FROM Products
--	IF @Sayi > 5000
--	BEGIN
--		SET @Metin= ('5 BÝNDEN FAZLA KAYIT VAR')
--	END
--	ELSE
--	BEGIN
--		SET @Metin=('5 BÝNDEN AZ KAYIT VAR')
--	END
--	RETURN @Metin
--END

--SELECT dbo.FN_KAYITGOSTER()



--CREATE FUNCTION FN_KAYITGOSTER2()
--RETURNS @KAYITSAYISI TABLE (ACIKLAMA NVARCHAR (50),TUTULANKAYIT INT)
--AS 
--BEGIN
--	DECLARE @Sayi INT 
--	DEClarE @Metin NVARCHAR (50)
--	SELECT @Sayi =COUNT(*) FROM Products
--	IF @Sayi > 5000
--	BEGIN
--		SET @Metin= ('5 BÝNDEN FAZLA KAYIT VAR')
--		INSERT INTO @KAYITSAYISI  VALUES (@Metin,@Sayi)
--	END
--	ELSE
--	BEGIN
--		SET @Metin=('5 BÝNDEN AZ KAYIT VAR')
--		INSERT INTO @KAYITSAYISI  VALUES (@Metin,@Sayi)
--	END
--	RETURN 
--END

--SELECT * FROM DBO.FN_KAYITGOSTER2()


--IF EXISTS 
--(SELECT * FROM sys.tables WHERE NAME ='Customers')
--	BEGIN
--		PRINT ('TABLO MEVCUT')
--	END
--ELSE
--	BEGIN
--		PRINT ('TABLO MEVCUT DEÐL')
--	END
	
